### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [brianshannan/nats-rs#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by brianshannan** [comment]
I don't think so, I just haven't gotten around to using serde yet.

**Comment by brianshannan** [comment]
Resolved in 1010dcecdeac7ba1b66c9f93f7cf11acfb0da468
